language: python
python:
- "3.6.1"
cache: pip
install:
- pip install -r requirements.txt
services:
- postgresql
before_script:
- psql -c 'create database test_bucket;' -U postgres
script: nose2 -v --with-coverage
after_success: coveralls